import React from 'react';
import {StyleSheet} from 'react-native';
import {
    Button,
    Input,
    FormControl,
    View,
    Text,
    Image,
    ScrollView,
    Box,
    Divider,
    Stack,
} from 'native-base';
import Icon from 'react-native-vector-icons/Feather';

const GridSeat = () => {
    return (
        <View>
            <Box backgroundColor="white" borderRadius="md" mt="5">
                <Divider
                    mt={3}
                    mx={10}
                    width="3/4"
                    borderRadius="md"
                    height="3"
                    backgroundColor="#62B6B7"
                />
                <Box>
                    <Stack direction="row" space={3} px="2" pt="8">
                        {/* Konten Grid Seat */}
                        <Box>
                            <Stack direction="column" space={3}>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#62B6B7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#62B6B7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#62B6B7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                            </Stack>
                        </Box>
                        <Box>
                            <Stack direction="column" space={3}>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                            </Stack>
                        </Box>
                        {/* Konten Grid Seat End*/}
                    </Stack>
                </Box>
                <Text mt="8" px="5">
                    Seating key
                </Text>
                <Box mt="5">
                    <Stack direction="row" space={20} px="3">
                        <Stack direction="row" space={2} alignItems="center">
                            <Icon name="arrow-down" size={25} />
                            <Text fontSize={20}>A - G</Text>
                        </Stack>
                        <Stack direction="row" space={2} alignItems="center">
                            <Icon name="arrow-right" size={25} />
                            <Text fontSize={20}>A - G</Text>
                        </Stack>
                    </Stack>
                </Box>
                <Box px="5" mt="5" mb="10">
                    <Stack direction="row" space={10}>
                        <Box>
                            <Stack direction="column" space={2}>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Text>Available</Text>
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Text>Sold</Text>
                                </Stack>
                            </Stack>
                        </Box>
                        <Box>
                            <Stack direction="row" space={2}>
                                <Box
                                    w="14"
                                    h="14"
                                    backgroundColor="#62B6B7"
                                    borderRadius="2"
                                />
                                <Text>Selected</Text>
                            </Stack>
                        </Box>
                    </Stack>
                </Box>
            </Box>
        </View>
    );
};

export default GridSeat;
