import React from 'react';
import {StyleSheet} from 'react-native';
import {
    Button,
    Input,
    FormControl,
    View,
    Text,
    Image,
    ScrollView,
    Box,
    Divider,
    Stack,
} from 'native-base';
import Icon from 'react-native-vector-icons/Feather';
import {Formik} from 'formik';
import * as yup from 'yup';

const loginSchemaValidation = yup.object().shape({
    email: yup
        .string()
        .email('Please enter valid email')
        .required('Email address is Required'),
    password: yup
        .string()
        .min(8, ({min}) => `Password must be at least ${min} characters`)
        .required('Password is required'),
});

const TesForm = () => {
    return (
        <>
            <Box backgroundColor="white" borderRadius="md">
                <Divider
                    mt={3}
                    mx={10}
                    width="3/4"
                    borderRadius="md"
                    height="3"
                    backgroundColor="#9570FE"
                />
                <Box>
                    <Stack direction="row" space={6} px="5" pt="8">
                        {/* Konten Grid Seat */}
                        <Box>
                            <Stack direction="column" space={3}>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#5F2EEA"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#5F2EEA"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#5F2EEA"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                            </Stack>
                        </Box>
                        <Box>
                            <Stack direction="column" space={3}>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                </Stack>
                            </Stack>
                        </Box>
                        {/* Konten Grid Seat End*/}
                    </Stack>
                </Box>
                <Text mt="8" px="5">
                    Seating key
                </Text>
                <Box mt="5">
                    <Stack direction="row" space={20} px="3">
                        <Stack direction="row" space={2} alignItems="center">
                            <Icon name="arrow-down" size={25} />
                            <Text fontSize={20}>A - G</Text>
                        </Stack>
                        <Stack direction="row" space={2} alignItems="center">
                            <Icon name="arrow-right" size={25} />
                            <Text fontSize={20}>A - G</Text>
                        </Stack>
                    </Stack>
                </Box>
                <Box px="5" mt="5">
                    <Stack direction="row" space={10}>
                        <Box>
                            <Stack direction="column" space={2}>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#D6D8E7"
                                        borderRadius="2"
                                    />
                                    <Text>Available</Text>
                                </Stack>
                                <Stack direction="row" space={2}>
                                    <Box
                                        w="14"
                                        h="14"
                                        backgroundColor="#6E7191"
                                        borderRadius="2"
                                    />
                                    <Text>Sold</Text>
                                </Stack>
                            </Stack>
                        </Box>
                        <Box>
                            <Stack direction="row" space={2}>
                                <Box
                                    w="14"
                                    h="14"
                                    backgroundColor="#5F2EEA"
                                    borderRadius="2"
                                />
                                <Text>Selected</Text>
                            </Stack>
                        </Box>
                    </Stack>
                </Box>
            </Box>
        </>
    );
};

export default TesForm;
